##-*- coding: utf-8 -*-
"""AIML-FACEMASK.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1qLSTvqp-ylon9Xy_O-o8czIql-OYEsOe
"""
# This project is organized into modules for data prep, model building, and Flask deployment.
print("Project structure complete.")

# Cell removed as it was a placeholder.

"""# Face Mask Detection with Live Alert System
This notebook follows a modular approach to build a real-time mask detector.

### M 1: Environment Setup and Data Preparation
First, we need to import our libraries and define how we will handle the image data.
"""

import cv2
import os
import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img

# Define constants
INIT_LR = 1e-4
EPOCHS = 20
BS = 32
DIRECTORY = "AIML_LIVE1/dataset/"
CATEGORIES = ["with_mask", "without_mask"]

print("Modules imported successfully.")


# Create the dataset directory structure
os.makedirs('AIML_LIVE1/dataset/with_mask/', exist_ok=True)
os.makedirs('AIML_LIVE1/dataset/without_mask/', exist_ok=True)

print("Directories created: dataset/with_mask and dataset/without_mask")
#=====================##################=====================################=====================
data = []
labels = []

# Loop over the categories and load images
for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category)
    if not os.path.exists(path):
        print(f"Directory missing: {path}")
        continue
        
    images = os.listdir(path)
    if len(images) == 0:
        print(f"Warning: {path} is empty. Please upload images to this folder.")
        continue

    for img in images:
        img_path = os.path.join(path, img)
        try:
            image = load_img(img_path, target_size=(224, 224))
            image = img_to_array(image)
            image = image / 255.0 # Normalization

            data.append(image)
            labels.append(category)
        except Exception as e:
            print(f"Could not load image {img}: {e}")

if len(data) > 0:
    # Convert to numpy arrays
    data = np.array(data, dtype="float32")
    labels = np.array(labels)

    # Perform one-hot encoding on the labels
    lb = LabelBinarizer()
    labels = lb.fit_transform(labels)
    labels = to_categorical(labels)

    (trainX, testX, trainY, testY) = train_test_split(data, labels, test_size=0.20, stratify=labels, random_state=42)
    print(f"Successfully loaded {len(data)} images. Data split into {len(trainX)} training and {len(testX)} test samples.")
else:
    print("No data found. Please upload images to the dataset folders and try again.")


"""### M 2: Building the CNN Model Architecture
We will create a specialized CNN to classify images into 'Mask' or 'No Mask'.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input

def build_model():
    model = Sequential([
        Input(shape=(224, 224, 3)),
        Conv2D(32, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Flatten(),
        Dropout(0.5),
        Dense(128, activation='relu'),
        Dense(2, activation='softmax')
    ])

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

mask_model = build_model()
mask_model.summary()

"""### M3: Flask Deployment Structure
Since you want to deploy on Flask, you need a specific folder structure. Run this cell to create the necessary directories for your local deployment.
"""

# Ensure the directory structure exists
os.makedirs('AIML_LIVE1/flask_app/templates', exist_ok=True)
os.makedirs('AIML_LIVE1/flask_app/static', exist_ok=True)

# Recreate the index.html template inside the templates folder
index_html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Face Mask Detection</title>
    <style>
        body { text-align: center; font-family: Arial, sans-serif; }
        img { border: 2px solid #ddd; border-radius: 4px; padding: 5px; width: 80%; }
    </style>
       body { text-align: center; font-family: Arial, sans-serif; }
       h1 { margin-top: 20px; }
       .camera-feed { margin-top: 20px; }
       img { border: 2px solid #ddd; border-radius: 4px; padding: 5px; width: 80%; }
       .info { margin-top: 20px; font-size: 1.2em; }
    </style>
</head>
<body>
    <h1>Live Alert System</h1>
    <img src="{{ url_for('video_feed') }}" width="80%">
</body>
</html>
</p> each person detected without a mask will trigger an alert.</p>
</p> each person detected with identification will be logged.</p>
</body>
</html>
"""

with open('AIML_LIVE1/flask_app/templates/index.html', 'w') as f:
    f.write(index_html_content)

print("Successfully created AIML_LIVE1/flask_app/templates/index.html")

# Create a basic index.html for Flask
with open('AIML_LIVE1/flask_app/templates/index.html', 'w') as f:
    f.write('<html><body><h1>Face Mask Detection Live Stream</h1><img src="{{ url_for(\'video_feed\') }}"></body></html>')

print("Flask directory structure created.")

"""### M6: Data Augmentation and Training
This module uses Keras's `ImageDataGenerator` to artificially expand your dataset and then trains the model.
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Construct the training image generator for data augmentation
aug = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.15,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    horizontal_flip=True,
    fill_mode="nearest")

print("Data augmentation module ready.")

# To train (assuming you have your data loaded):
if 'trainX' in locals() and len(trainX) > 0:
    print("Starting training...")
H = mask_model.fit(
    aug.flow(
        trainX,
        trainY,
        batch_size=BS
    ),
    validation_data=(
        testX,
        testY
    ),
    epochs=EPOCHS
)

# To save for Flask deployment:
#mask_model.save('AIML_LIVE1/flask_app/mask_detector.model', save_format='h5')
MODEL_PATH = "AIML_LIVE1/flask_app/mask_detector.keras"

mask_model.save(MODEL_PATH)

print("Model training completed.")
print("Model saved successfully.")


"""### M4: Flask Application and Live Inference
This module creates the `app.py` file which handles the webcam stream, face detection using Haar Cascades, and the prediction logic.
"""
final_flask_app = """
import cv2
import os
import numpy as np
from flask import Flask, render_template, Response
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
from dotenv import load_dotenv
import smtplib
from email.message import EmailMessage

app = Flask(__name__)
load_dotenv()

# 1. Load Resources
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
# model = load_model('mask_detector.model') # Ensure model is in the same folder

def send_email_alert():
    msg = EmailMessage()
    msg.set_content("Face Mask Violation Detected!")
    msg['Subject'] = 'SECURITY ALERT'
    msg['From'] = os.getenv('EMAIL_USER')
    msg['To'] = os.getenv('EMAIL_RECEIVER')
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(os.getenv('EMAIL_USER'), os.getenv('EMAIL_PASS'))
            server.send_message(msg)
    except: pass

def generate_frames():
    camera = cv2.VideoCapture(0)
    while True:
        success, frame = camera.read()
        if not success: break
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.1, 4)

        for (x, y, w, h) in faces:
            face_img = frame[y:y+h, x:x+w]
            face_img = cv2.resize(cv2.cvtColor(face_img, cv2.COLOR_BGR2RGB), (224, 224))
            face_img = img_to_array(face_img) / 255.0
            face_img = np.expand_dims(face_img, axis=0)

            # Prediction (Mocked until you save your model)
            # (mask, withoutMask) = model.predict(face_img)[0]
            label = "Mask" # Logic: "No Mask" if withoutMask > mask else "Mask"
            color = (0, 255, 0) if label == "Mask" else (0, 0, 255)

            if label == "No Mask":
                cv2.putText(frame, "ALERT", (x, y-40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)
                # send_email_alert()

            cv2.rectangle(frame, (x, y), (x+w, y+h), color, 2)
            cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)

        ret, buffer = cv2.imencode('.jpg', frame)
        yield (b'--frame\\r\\n' b'Content-Type: image/jpeg\\r\\n\\r\\n' + buffer.tobytes() + b'\\r\\n')

@app.route('/')
def index(): return render_template('index.html')

@app.route('/video_feed')
def video_feed(): return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
"""

with open('AIML_LIVE1/flask_app/app.py', 'w') as f:
    f.write(final_flask_app)

print("Final unified app.py generated in /AIML_LIVE1/flask_app/")

#print("flask_app/app.py has been generated.")


def trigger_alert(frame, x, y):
    """
    This function draws a high-visibility alert on the frame.
    In a desktop app, you could also use 'os.system' to play a beep sound.
    """
    overlay = frame.copy()
    cv2.rectangle(overlay, (x, y-35), (x+150, y), (0, 0, 255), -1)
    cv2.putText(frame, "NO MASK ALERT!", (x+5, y-10),
                cv2.FONT_HERSHEY_DUPLEX, 0.6, (255, 255, 255), 1)
    return frame

print("Alert logic module defined.")

"""### M 8: Saving Your Trained Model
After training, you must save the model so the Flask application can load it without needing to re-train everything.
"""

# Execute this after your training loop is finished
# mask_model.save('flask_app/mask_detector.model', save_format='h5')

print("Code to save model ready. Use .h5 format for easy loading in Flask.")

"""### M 9: Integrated Alert System (Sound & Email)
We will now update the `trigger_alert` logic to include placeholders for system sounds and automated emails using Python's `smtplib`.
"""

import smtplib
from email.message import EmailMessage
import os
from email.message import EmailMessage
from dotenv import load_dotenv

# Load credentials from .env file
load_dotenv()
EMAIL_ADDRESS = os.getenv('EMAIL_USER')
EMAIL_PASSWORD = os.getenv('EMAIL_PASS')
RECEIVER_EMAIL = os.getenv('EMAIL_RECEIVER')

def send_email_alert():
    if not EMAIL_ADDRESS or not EMAIL_PASSWORD:
        print("Email credentials missing in .env file!")
        return

    msg = EmailMessage()
    msg.set_content("Violation Detected: Someone entered the zone without a mask.")
    msg['Subject'] = 'FACE MASK ALERT'
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = RECEIVER_EMAIL

    try:
        # For Gmail, use port 465 for SSL
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            server.send_message(msg)
        print("Email Alert Sent!")
    except Exception as e:
        print(f"Failed to send email: {e}")

def play_sound():
    # For local Windows/Linux/Mac deployment:
    # import winsound; winsound.Beep(2500, 1000)
    # or use: os.system('say "Please wear a mask"') # Mac
    print("\a") # Console Beep

import os

# We define the lines explicitly to avoid triple-quote indentation issues
env_lines = [
    "EMAIL_USER=your_email@gmail.com",
    "EMAIL_PASS=your_app_specific_password",
    "EMAIL_RECEIVER=security_admin@gmail.com"
]

# Write the file with clean line breaks
with open('AIML_LIVE1/flask_app/.env', 'w', encoding='utf-8') as f:
    f.write('\n'.join(env_lines))

print("Cleaned .env file created at AIML_LIVE1/flask_app/.env")
# Display the raw content to verify no extra spaces exist
with open('AIML_LIVE1/flask_app/.env', 'r') as f:
    print(f"File Content:\n{repr(f.read())}")

"""### M 10: Updating the Main Flask Loop
This replaces the previous `app.py` logic to integrate the trained model and the new alert triggers.
"""

updated_flask_code = """
 ... (Previous imports) ...
 Inside generate_frames():

for (x, y, w, h) in faces:
     ... (Preprocessing code) ...

     pred = model.predict(face_img)
     (mask, withoutMask) = pred[0]

     if withoutMask > mask:
         label = "No Mask"
         color = (0, 0, 255)
         frame = trigger_alert(frame, x, y)
         play_sound()
         # send_email_alert() # Call sparingly to avoid spam
     else:
         label = "Mask"
        color = (0, 255, 0)
"""

print("Integration logic drafted. Remember to uncomment prediction lines after training!")

